### ISSUE TITLE
the final mIOU for class200 is 0.36?

### ISSUE THREAD

**Issue by saysth** [Juliachang/SC-CAM#8]
class  0 background   IU 0.76
class  1 aeroplane    IU 0.39
class  2 bicycle      IU 0.30
class  3 bird         IU 0.40
class  4 boat         IU 0.36
class  5 bottle       IU 0.55
class  6 bus          IU 0.69
class  7 car          IU 0.54
class  8 cat          IU 0.62
class  9 chair        IU 0.28
class 10 cow          IU 0.51
class 11 diningtable  IU 0.46
class 12 dog          IU 0.57
class 13 horse        IU 0.59
class 14 motorbike    IU 0.59
class 15 person       IU 0.49
class 16 pottedplant  IU 0.43
class 17 sheep        IU 0.56
class 18 sofa         IU 0.50
class 19 train        IU 0.53
class 20 tvmonitor    IU 0.47
meanIOU: 0.5028162179859049

class  0 background   IU 0.62
class  1 aeroplane    IU 0.23
class  2 bicycle      IU 0.23
class  3 bird         IU 0.21
class  4 boat         IU 0.30
class  5 bottle       IU 0.51
class  6 bus          IU 0.55
class  7 car          IU 0.39
class  8 cat          IU 0.36
class  9 chair        IU 0.20
class 10 cow          IU 0.41
class 11 diningtable  IU 0.34
class 12 dog          IU 0.28
class 13 horse        IU 0.39
class 14 motorbike    IU 0.41
class 15 person       IU 0.26
class 16 pottedplant  IU 0.38
class 17 sheep        IU 0.36
class 18 sofa         IU 0.42
class 19 train        IU 0.47
class 20 tvmonitor    IU 0.39
meanIOU: 0.36679235052055154

**Comment by wasidennis** [comment]
@saysth Yes, since now each category has 10 response maps from each of the sub-categories, it is not straightforward to simply combine 10 response maps to obtain the final one for the IoU calculation. And thanks for pointing it out, but to clarify, the goal here is to introduce this additional objective for improving feature representations in the classification backbone training. IoU reported from the sub-category classifier is only for the reference here.

**Comment by OpencvW** [comment]
@saysth @wasidennis   DId you meet this issue, the final mIoU result is 0 except for the background? How to solve this problem？ Thanks
